stages:
  embed_baseline:
    foreach:
      - gallery
      - query
    do:
      cmd: python scripts/embed_with_clip.py --data-root "data/In-shop Clothes Retrieval Benchmark" --split ${item} --batch-size 32 --output data/embeddings/baseline/${item}.csv
      deps:
        - scripts/embed_with_clip.py
        - data/In-shop Clothes Retrieval Benchmark/Eval/list_eval_partition.txt
        - data/In-shop Clothes Retrieval Benchmark/Img/
      outs:
        - data/embeddings/baseline/${item}.csv
  evaluate:
    foreach:
      - baseline
      # Add other methods here if needed
    do:
      cmd: python scripts/evaluate_similiarity_search.py --eval-file "data/In-shop Clothes Retrieval Benchmark/Eval/list_eval_partition.txt" --gallery-embeddings-csv data/embeddings/${item}/gallery.csv --query-embeddings-csv data/embeddings/${item}/query.csv --output-file data/results/${item}_eval.csv
      deps:
        - scripts/evaluate_similiarity_search.py
        - data/In-shop Clothes Retrieval Benchmark/Eval/list_eval_partition.txt
        - data/embeddings/${item}/gallery.csv
        - data/embeddings/${item}/query.csv
      outs:
        - data/results/${item}_eval.csv
  train_lora_clip:
    cmd: python scripts/train_clip_lora_lightning.py
    deps:
      - scripts/train_clip_lora_lightning.py
      - data/In-shop Clothes Retrieval Benchmark/Eval/list_eval_partition.txt
      - data/In-shop Clothes Retrieval Benchmark/Img/
    outs:
      - models/clip_vit_lora_lightning/final.ckpt
      - models/clip_vit_lora_lightning/final_lora
